spring:
  cloud:
    config:
      enabled: false
  kafka:
    listener:
      auto-startup: false

app:
  kafka:
    topics:
      payments-processed: payments-processed-topic
      orders-created: orders-created-topic
